### PR TITLE
Archive repository and all its files

### PR DESCRIPTION
**Pull request by chmouel**

### CODE REVIEW

**Comment by rhuss** [comment]
@chmouel Can we please keep this repository open ? It is actually referenced in various presentations to compare the various available Docker Maven plugins. At least we should keep the original README as reference. Also happy to take care about it and fix issue when they come in, and, if time permits to update it with the latest information.

**Comment by rhuss** [comment]
@chmouel could please also restore the old state ? thanks!

**Comment by chmouel** [comment]
Sure no problem, there is unfortuntely a few security issue in there as
reported by github,  would it be possible to help us fixing those ?

**Comment by rhuss** [comment]
Yes, of course!

**Comment by chmouel** [comment]
@rhuss I have [updated](https://github.com/fabric8io/shootout-docker-maven/commit/c22bed6bdee0c9c55db53acf1b443834d88fe7c9) to 7.0.91 tomcat which seems to fix the security issue, let me know if that works for you,

**Pull request merged**
